# Generated by Django 5.1.1 on 2024-09-27 19:07

import collab_poc_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yjs', collab_poc_app.models.YDocField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contents', models.TextField()),
            ],
        ),
    ]
